### ISSUE TITLE
legend!

### ISSUE THREAD

**Issue by willfootwill** [sweharris/dumb_usb_printer#1]
Thank you!

Now printing to my mx80 from a pi

It's working with my `Prolific` branded usb cable too?

We had a beeb growing up, with a Citizen printer. My brother has gone back down that rabbit hole, plus archimedes stuff which was grail at the time haha.

Think these Epsons were more popular in N America?

Thanks again

Englishman living in Toronto

**Comment by sweharris** [comment]
Glad its working for you; the problem I had with prolific is that it'd work once and then start ignoring additional requests.  Maybe you've got a better adapter :-)

My secondary school only had a commodore printer (for the PETs), but sixth form and Uni had Epson's.
